export const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR';
export const SET_GLOBAL_SUCCESS = 'SET_GLOBAL_SUCCESS';

export const GET_ALL_TRUCKS_SUCCESS = 'GET_ALL_TRUCKS_SUCCESS';
export const LOAD_TRUCK_CARE_GROUP_SUCCESS = 'LOAD_TRUCK_CARE_GROUP_SUCCESS';

export const GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS';
