export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR';

export const GET_ALL_TRUCKS_SUCCESS = 'GET_ALL_TRUCKS_SUCCESS';
export const GET_TRUCK_CARE_GROUP_SUCCESS = 'GET_TRUCK_CARE_GROUP_SUCCESS';
